# Generated by Django 5.1.6 on 2025-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchinh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('thongtin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TBVTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=255)),
                ('thongtin', models.CharField(max_length=255)),
            ],
        ),
    ]
